examples=[  ## Neglect retrieved wiki of series
{
    "type_of_push_notification": "cast-driven",
    "number_of_push_notifications": 1,
    "name_of_series": "Uncover My Love",
    "series_content": "Lam Dim, husband of Mor Tin, is one of the best MC in the world. He has an affair with Tam Lin So recently when emeting her in her secondary school festival.",
    "series_description": "One of the best MCs in the country, Lam Dim, is a married man. It has gotten to the point that he says he is bored of the marriage. This saying of his sparks an idea to start a new love with a 17-year-old girl.",
    "name_of_cast": "Kim Zhong Shok",
    "type_of_cast": "Main Cast",
    "nickname_of_cast": "Kim Kim",
    "quote_of_cast": None,
    "interesting_fact_of_cast": None,
    "character_in_series_acted_by_cast": "Lam Dim",
    "demographics_of_target_receiver": "20-40 years old, fan of the cast",
    "base_push_example": None,
    "local_trend_in_malaysia": None,
    "include_emoji": True,
    "include_slangs": True,
    "additional_requirements": None,
    "english_title": "Caught Red-Handed! Kim Kim in a Secret Affair on Uncover My Love!", 
    "english_body": "A shocking romance between Kim Zhong Shok and a much younger lover! 😱 Is it true love or just a scandal? Find out on Uncover My Love! 📺 Watch now and get all the juicy details! 💥 #DramaAlert #MustWatch",
    "malay_title": "Tertangkap Basah! Kim Kim dalam Skandal Cinta di Uncover My Love!", 
    "malay_body": "Percintaan mengejutkan antara Kim Zhong Shok dan kekasih yang jauh lebih muda! 😱 Cinta sejati atau skandal? Ketahui di Uncover My Love! 📺 Tonton sekarang dan dapatkan semua butiran menarik! 💥 #DramaAlert #MestiTonton"
},
{
    "type_of_push_notification": "content-driven",
    "number_of_push_notifications": 1,
    "name_of_series": "Twisted Love",
    "series_content": "Roy In Shek confessed to Lee Tin Wai, however being brutally rejected in front of the other six friends. Roy In Shek cried and left with his broken heart",
    "series_description": "There are 7 boys and girls in the TongKong School, they relationship are messily entangled, how would they continue their remaining 2 years in the school, facing all these complicated relationships?",
    "name_of_cast": None,
    "type_of_cast": "Main Cast",
    "nickname_of_cast": None,
    "quote_of_cast": None,
    "interesting_fact_of_cast": None,
    "character_in_series_acted_by_cast": None,
    "demographics_of_target_receiver": "everyone",
    "base_push_example": None,
    "local_trend_in_malaysia": None,
    "include_emoji": True,
    "include_slangs": True,
    "additional_requirements": None,
    "english_title": "Seven Teens, One Twisted Love Story!", 
    "english_body": "Heartbreak and betrayal! Roy In Shek is rejected in the face, being public shamed in front of the other six friends. 💔 Can you steal his broken heart? Watch Twisted Love on Viu now! 💫 Dive into the drama and see if love can conquer all! 🌟 #TeenDrama #LoveAndHate #CharacterName #SeriesName", 
    "malay_title": "Tujuh Remaja, Satu Kisah Cinta Berliku!", 
    "malay_body": "Kekecewaan dan pengkhianatan ketika Roy In Shek menghadapi penolakan terakhir. 💔 Bolehkah anda memenangi hati mereka? Tonton Twisted Love di Viu sekarang! 💫 Selami drama dan lihat jika cinta dapat menaklukkan segalanya! 🌟 #DramaRemaja #CintaDanBenci #CharacterName #SeriesName"
},
{
    "type_of_push_notification": "cast-driven",
    "number_of_push_notifications": 1,
    "name_of_series": "Loving Storm",
    "series_content": "Reyna confessed to Lee Tin Wai, however being brutally rejected inin the storm, leaving herself alone standing in the heavy rain and thunder.",
    "series_description": "Young couple Reyna and Lin navigate the highs and lows of their tumultuous relationship, filled with love, laughter, and heartbreak. After a painful breakup, they must confront their feelings and challenges to find their way back to each other once more.",
    "name_of_cast": "Tam Qin",
    "type_of_cast": "Main Cast",
    "nickname_of_cast": None,
    "quote_of_cast": None,
    "interesting_fact_of_cast": None,
    "character_in_series_acted_by_cast": "Reyna",
    "demographics_of_target_receiver": "fan of Tam Qin",
    "base_push_example": None,
    "local_trend_in_malaysia": "Typhoon number 8 is announced at nine am this morning, students have one day of extra holiday",
    "include_emoji": True,
    "include_slangs": True,
    "additional_requirements": None,
    "english_title": "Confession under Typhoon 8! Tam Qin Braving the Storm for Love!", 
    "english_body": "In the midst of a typhoon, Tam Qin as Reyna makes a tearful confession! 🌩️ Go and find Tam Qin now in Loving Storm and you may be the one to get his heart healed! 😭 Don’t miss this emotional rollercoaster and watch Loving Storm now! 🎢 #StormyLove #Emotional", 
    "malay_title": "Pengakuan Taufan! Tam Qin Menghadapi Ribut untuk Cinta!", 
    "malay_body": "Di tengah-tengah taufan, Tam Qin sebagai Reyna membuat pengakuan yang penuh air mata! 🌩️ Ayo, cari Tam Qin sekarang di Loving Storm dan mungkin kamu yang akan menyembuhkan hatinya! 😭 Jangan lepaskan rollercoaster emosi ini! Tonton Loving Storm sekarang! 🎢 #CintaRibut #Emosi"
},
# {
#     "type_of_push_notification": "cast-driven",
#     "number_of_push_notifications": 1,
#     "name_of_series": ,
#     "series_content": ,
#     "series_description": ,
#     "name_of_cast": ,
#     "type_of_cast": "Main Cast",
#     "nickname_of_cast": ,
#     "quote_of_cast": ,
#     "interesting_fact_of_cast": ,
#     "character_in_series_acted_by_cast": ,
#     "demographics_of_target_receiver": ,
#     "base_push_example": None,
#     "local_trend_in_malaysia": ,
#     "include_emoji": True,
#     "include_slangs": True,
#     "additional_requirements": None,
#     "english_title": "Possessed?! Kim Zhong Shok Faces a Demonic Entity in {Series Name}!", 
#     "english_body": "A terrifying encounter as Kim Zhong Shok battles a sinister force that haunts their every move! 😱 Will they survive the night or become the next victim? The shadows are closing in, and every step could be their last. Find out on {Series Name}! 📺 Witness the spine-chilling horror unfold! 🕯️👻 #Horror #CastName #SeriesName", 
#     "malay_title": "Dirasuk?! Kim Zhong Shok Berdepan Entiti Jahat dalam {Series Name}!", 
#     "malay_body": "Pertemuan menakutkan apabila Kim Zhong Shok melawan kuasa jahat yang menghantui setiap langkah mereka! 😱 Adakah mereka akan selamat malam ini atau menjadi mangsa seterusnya? Bayang-bayang semakin menghampiri, dan setiap langkah boleh menjadi yang terakhir. Ketahui di {Series Name}! 📺 Saksikan seram yang mengerikan! 🕯️👻 #Seram #CastName #SeriesName"
# },
# {
#     "type_of_push_notification": "cast-driven",
#     "number_of_push_notifications": 1,
#     "name_of_series": ,
#     "series_content": ,
#     "series_description": ,
#     "name_of_cast": ,
#     "type_of_cast": "Main Cast",
#     "nickname_of_cast": ,
#     "quote_of_cast": ,
#     "interesting_fact_of_cast": ,
#     "character_in_series_acted_by_cast": ,
#     "demographics_of_target_receiver": ,
#     "base_push_example": None,
#     "local_trend_in_malaysia": ,
#     "include_emoji": True,
#     "include_slangs": True,
#     "additional_requirements": None,
#     "english_title": "Haunted House Horror! Tam Long Tin Trapped with No Escape!", 
#     "english_body": "Locked inside a haunted mansion, Tam Long Tin must uncover deadly secrets to survive! 🏚️ Every corner hides a new terror, and the walls seem to whisper their doom. Can they escape the clutches of the supernatural or will they be trapped forever? Tune in to {Series Name} for the ultimate scare! 🔪👀 #Haunted #CharacterName #SeriesName", 
#     "malay_title": "Seram Rumah Berhantu! Tam Long Tin Terperangkap Tanpa Jalan Keluar!", 
#     "malay_body": "Terkunci dalam rumah agam berhantu, Tam Long Tin mesti membongkar rahsia maut untuk terus hidup! 🏚️ Setiap sudut menyembunyikan ketakutan baru, dan dinding seolah-olah berbisik tentang kemusnahan mereka. Bolehkah mereka melarikan diri dari cengkaman supernatural atau akan terperangkap selama-lamanya? Tonton {Series Name} untuk ketakutan yang paling hebat! 🔪👀 #Berhantu #CharacterName #SeriesName"
# },
# {
#     "type_of_push_notification": "cast-driven",
#     "number_of_push_notifications": 1,
#     "name_of_series": ,
#     "series_content": ,
#     "series_description": ,
#     "name_of_cast": ,
#     "type_of_cast": "Main Cast",
#     "nickname_of_cast": ,
#     "quote_of_cast": ,
#     "interesting_fact_of_cast": ,
#     "character_in_series_acted_by_cast": ,
#     "demographics_of_target_receiver": ,
#     "base_push_example": None,
#     "local_trend_in_malaysia": ,
#     "include_emoji": True,
#     "include_slangs": True,
#     "additional_requirements": None,
#     "english_title": "Heroic Stand! Kim Zhong Shok Saves the Day in {Series Name}!", 
#     "english_body": "With the city in peril, Kim Zhong Shok steps up to save the day! ‘I am Iron Man,’ they declare, facing off against the ultimate villain. 💥 Explosions, high-speed chases, and epic battles await. Will they triumph or fall? Don’t miss the action on {Series Name}! 🦸‍♂️⚡ #Hero #CastName #SeriesName", 
#     "malay_title": "Pendekar Berani! Kim Zhong Shok Menyelamatkan Hari dalam {Series Name}!", 
#     "malay_body": "Dengan bandar dalam bahaya, Kim Zhong Shok melangkah untuk menyelamatkan hari! ‘Saya Iron Man,’ mereka mengisytiharkan, berhadapan dengan penjahat utama. 💥 Letupan, kejaran berkelajuan tinggi, dan pertempuran epik menanti. Adakah mereka akan menang atau jatuh? Jangan lepaskan aksi dalam {Series Name}! 🦸‍♂️⚡ #Hero #CastName #SeriesName"
# },
# {
#     "type_of_push_notification": "cast-driven",
#     "number_of_push_notifications": 1,
#     "name_of_series": ,
#     "series_content": ,
#     "series_description": ,
#     "name_of_cast": ,
#     "type_of_cast": "Main Cast",
#     "nickname_of_cast": ,
#     "quote_of_cast": ,
#     "interesting_fact_of_cast": ,
#     "character_in_series_acted_by_cast": ,
#     "demographics_of_target_receiver": ,
#     "base_push_example": None,
#     "local_trend_in_malaysia": ,
#     "include_emoji": True,
#     "include_slangs": True,
#     "additional_requirements": None,
#     "english_title": "Epic Battle! Kim Kim vs. Villain in {Series Name}!", 
#     "english_body": "The ultimate showdown is here! Kim Kim faces off against their greatest foe. ‘Rich is my superpower,’ they quip, ready for battle. 💪 The fate of the world hangs in the balance. Watch {Series Name} for the epic clash of titans! 🦇🔥 #Heroic #Nickname #SeriesName", 
#     "malay_title": "Pertempuran Epik! Kim Kim vs. Penjahat dalam {Series Name}!", 
#     "malay_body": "Pertarungan terakhir sudah tiba! Kim Kim berhadapan dengan musuh terbesar mereka. ‘Kekayaan adalah kuasa super saya,’ mereka berseloroh, bersedia untuk bertarung. 💪 Nasib dunia tergantung pada keseimbangan. Tonton {Series Name} untuk pertembungan epik para titan! 🦇🔥 #Heroik #Nickname #SeriesName"
# },
# {
#     "type_of_push_notification": "cast-driven",
#     "number_of_push_notifications": 1,
#     "name_of_series": ,
#     "series_content": ,
#     "series_description": ,
#     "name_of_cast": ,
#     "type_of_cast": "Main Cast",
#     "nickname_of_cast": ,
#     "quote_of_cast": ,
#     "interesting_fact_of_cast": ,
#     "character_in_series_acted_by_cast": ,
#     "demographics_of_target_receiver": ,
#     "base_push_example": None,
#     "local_trend_in_malaysia": ,
#     "include_emoji": True,
#     "include_slangs": True,
#     "additional_requirements": None,
#     "english_title": "Love in the Air! Kim Zhong Shok Finds Romance in {Series Name}!", 
#     "english_body": "Sparks fly as Kim Zhong Shok meets their soulmate in the most unexpected place! 💖 Will love conquer all or will secrets tear them apart? Passion, heartbreak, and unforgettable moments await. Find out in {Series Name}! 🌹✨ #Romance #CastName #SeriesName", 
#     "malay_title": "Cinta di Udara! Kim Zhong Shok Menemui Romantik dalam {Series Name}!", 
#     "malay_body": "Percikan api terbang apabila Kim Zhong Shok bertemu pasangan jiwa mereka di tempat yang paling tidak dijangka! 💖 Adakah cinta akan menaklukkan segalanya atau rahsia akan memisahkan mereka? Keghairahan, kekecewaan, dan detik-detik yang tidak dapat dilupakan menanti. Ketahui dalam {Series Name}! 🌹✨ #Romantik #CastName #SeriesName"
# },
# {
#     "type_of_push_notification": "cast-driven",
#     "number_of_push_notifications": 1,
#     "name_of_series": ,
#     "series_content": ,
#     "series_description": ,
#     "name_of_cast": ,
#     "type_of_cast": "Main Cast",
#     "nickname_of_cast": ,
#     "quote_of_cast": ,
#     "interesting_fact_of_cast": ,
#     "character_in_series_acted_by_cast": ,
#     "demographics_of_target_receiver": ,
#     "base_push_example": None,
#     "local_trend_in_malaysia": ,
#     "include_emoji": True,
#     "include_slangs": True,
#     "additional_requirements": None,
#     "english_title": "Heartfelt Confession! Tam Long Tin Opens Up About Their Feelings!", 
#     "english_body": "In a tender moment, Tam Long Tin confesses their love amidst chaos. 💬 Will it end in a kiss or heartbreak? The tension is palpable, and every word could change their fate. Watch {Series Name} to see the emotional rollercoaster! 💔💑 #LoveStory #CharacterName #SeriesName", 
#     "malay_title": "Pengakuan Ikhlas! Tam Long Tin Membuka Tentang Perasaan Mereka!", 
#     "malay_body": "Dalam saat yang lembut, Tam Long Tin mengaku cinta mereka di tengah-tengah kekacauan. 💬 Adakah ia akan berakhir dengan ciuman atau kekecewaan? Ketegangan terasa, dan setiap perkataan boleh mengubah nasib mereka. Tonton {Series Name} untuk melihat rollercoaster emosi! 💔💑 #KisahCinta #CharacterName #SeriesName"
# },
# {
#     "type_of_push_notification": "cast-driven",
#     "number_of_push_notifications": 1,
#     "name_of_series": ,
#     "series_content": ,
#     "series_description": ,
#     "name_of_cast": ,
#     "type_of_cast": "Main Cast",
#     "nickname_of_cast": ,
#     "quote_of_cast": ,
#     "interesting_fact_of_cast": ,
#     "character_in_series_acted_by_cast": ,
#     "demographics_of_target_receiver": ,
#     "base_push_example": None,
#     "local_trend_in_malaysia": ,
#     "include_emoji": True,
#     "include_slangs": True,
#     "additional_requirements": None,
#     "english_title": "A 17-Year-Old and a 50-Year-Old?!", 
#     "english_body": "The shocking romance between Kim Zhong Shok (played by Kim Min Jae) and a much younger lover is turning heads. 🚨 Is it true love or a scandal? The controversial relationship is the talk of {Series Name}. Watch {Series Name} for the full story! 🔥 This is one you can’t miss! #Scandalous #AgeGap #CastName #SeriesName", 
#     "malay_title": "Seorang 17 Tahun dan 50 Tahun?!", 
#     "malay_body": "Percintaan mengejutkan antara Kim Zhong Shok (dilakonkan oleh Kim Min Jae) dan kekasih yang jauh lebih muda menarik perhatian. 🚨 Cinta sejati atau skandal? Hubungan kontroversi ini menjadi bualan dalam {Series Name}. Tonton {Series Name} untuk cerita penuh! 🔥 Ini yang anda tidak boleh lepaskan! #Skandal #JurangUsia #CastName #SeriesName"
# },
# {
#     "type_of_push_notification": "cast-driven",
#     "number_of_push_notifications": 1,
#     "name_of_series": ,
#     "series_content": ,
#     "series_description": ,
#     "name_of_cast": ,
#     "type_of_cast": "Main Cast",
#     "nickname_of_cast": ,
#     "quote_of_cast": ,
#     "interesting_fact_of_cast": ,
#     "character_in_series_acted_by_cast": ,
#     "demographics_of_target_receiver": ,
#     "base_push_example": None,
#     "local_trend_in_malaysia": ,
#     "include_emoji": True,
#     "include_slangs": True,
#     "additional_requirements": None,
#     "english_title": "Rejected in the Storm! Tam Long Tin Needs Your Help!", 
#     "english_body": "Alone and heartbroken in the storm, Tam Long Tin (played by Kim Min Jae) is in tears. 😭 Will you be their savior? The dramatic weather adds to the intensity of their heartbreak in {Series Name}. Comfort them by watching {Series Name} on Viu! 🌧️ Be the hero they need! 🦸‍♂️ #Heartbreak #ComfortNeeded #CharacterName #SeriesName", 
#     "malay_title": "Ditolak dalam Ribut! Tam Long Tin Perlukan Bantuan Anda!", 
#     "malay_body": "Bersendirian dan patah hati dalam ribut, Tam Long Tin (dilakonkan oleh Kim Min Jae) menangis. 😭 Adakah anda akan menjadi penyelamat mereka? Cuaca dramatik menambah intensiti kekecewaan mereka dalam {Series Name}. Hiburkan mereka dengan menonton {Series Name} di Viu! 🌧️ Jadi hero yang mereka perlukan! 🦸‍♂️ #PatahHati #PerluHiburan #CharacterName #SeriesName"
# },
# {
#     "type_of_push_notification": "cast-driven",
#     "number_of_push_notifications": 1,
#     "name_of_series": ,
#     "series_content": ,
#     "series_description": ,
#     "name_of_cast": ,
#     "type_of_cast": "Main Cast",
#     "nickname_of_cast": ,
#     "quote_of_cast": ,
#     "interesting_fact_of_cast": ,
#     "character_in_series_acted_by_cast": ,
#     "demographics_of_target_receiver": ,
#     "base_push_example": None,
#     "local_trend_in_malaysia": ,
#     "include_emoji": True,
#     "include_slangs": True,
#     "additional_requirements": None,
#     "english_title": "Love Triangle Drama! Kim Kim Caught in the Middle!", 
#     "english_body": "Drama unfolds as Kim Kim (played by Kim Min Jae) gets entangled in a love triangle! 🔥 Who will they choose? The love triangle adds layers of complexity to the relationships in {Series Name}. Find out on {Series Name}! The suspense is killing us! 😲 #LoveTriangle #Drama #Nickname #SeriesName", 
#     "malay_title": "Drama Cinta Segitiga! Kim Kim Terperangkap di Tengah!", 
#     "malay_body": "Drama terbongkar apabila Kim Kim (dilakonkan oleh Kim Min Jae) terjerat dalam cinta segitiga! 🔥 Siapa yang akan mereka pilih? Cinta segitiga menambah lapisan kerumitan kepada hubungan dalam {Series Name}. Ketahui di {Series Name}! Ketegangan ini membunuh kami! 😲 #CintaSegitiga #Drama #Nickname #SeriesName"
# },
# {
#     "type_of_push_notification": "cast-driven",
#     "number_of_push_notifications": 1,
#     "name_of_series": ,
#     "series_content": ,
#     "series_description": ,
#     "name_of_cast": ,
#     "type_of_cast": "Main Cast",
#     "nickname_of_cast": ,
#     "quote_of_cast": ,
#     "interesting_fact_of_cast": ,
#     "character_in_series_acted_by_cast": ,
#     "demographics_of_target_receiver": ,
#     "base_push_example": None,
#     "local_trend_in_malaysia": ,
#     "include_emoji": True,
#     "include_slangs": True,
#     "additional_requirements": None,
#     "english_title": "Secret Date Exposed! Kim Zhong Shok and Kim Zhong Shok Spotted Together!", 
#     "english_body": "Caught on camera! 👀 Kim Zhong Shok (played by Kim Min Jae) and Kim Zhong Shok (played by Kim Min Jae) spotted on a secret date. 💑 Are they the new power couple? The secret rendezvous is causing a buzz in {Series Name}. Watch {Series Name} for all the juicy details! This is the gossip you need! 🗣️ #SecretDate #NewCouple #CastName #SeriesName", 
#     "malay_title": "Temujanji Rahsia Terbongkar! Kim Zhong Shok dan Kim Zhong Shok Kelihatan Bersama!", 
#     "malay_body": "Tertangkap kamera! 👀 Kim Zhong Shok (dilakonkan oleh Kim Min Jae) dan Kim Zhong Shok (dilakonkan oleh Kim Min Jae) kelihatan dalam temujanji rahsia. 💑 Adakah mereka pasangan kuasa baru? Temujanji rahsia ini menimbulkan kekecohan dalam {Series Name}. Tonton {Series Name} untuk semua butiran menarik! Ini gosip yang anda perlukan! 🗣️ #TemujanjiRahsia #PasanganBaru #CastName #SeriesName"
# },
# {
#     "type_of_push_notification": "cast-driven",
#     "number_of_push_notifications": 1,
#     "name_of_series": ,
#     "series_content": ,
#     "series_description": ,
#     "name_of_cast": ,
#     "type_of_cast": "Main Cast",
#     "nickname_of_cast": ,
#     "quote_of_cast": ,
#     "interesting_fact_of_cast": ,
#     "character_in_series_acted_by_cast": ,
#     "demographics_of_target_receiver": ,
#     "base_push_example": None,
#     "local_trend_in_malaysia": ,
#     "include_emoji": True,
#     "include_slangs": True,
#     "additional_requirements": None,
#     "english_title": "Ultimate Betrayal! Tam Long Tin Stabbed in the Back!", 
#     "english_body": "In a dramatic turn of events, Tam Long Tin (played by Kim Min Jae) is betrayed by their closest ally. 💥 Can they recover? The betrayal shakes the very foundation of trust in {Series Name}. Watch {Series Name} now! This twist will leave you speechless! 😲 #Betrayal #PlotTwist #CharacterName #SeriesName", 
#     "malay_title": "Pengkhianatan Terhebat! Tam Long Tin Ditikam dari Belakang!", 
#     "malay_body": "Dalam peristiwa dramatik, Tam Long Tin (dilakonkan oleh Kim Min Jae) dikhianati oleh sekutu terdekat mereka. 💥 Bolehkah mereka pulih? Pengkhianatan ini menggoncang asas kepercayaan dalam {Series Name}. Tonton {Series Name} sekarang! Plot twist ini akan membuat anda terdiam! 😲 #Pengkhianatan #PlotTwist #CharacterName"
# }
]